!!!!! A NE PAS EXECUTER !!!!!

In [1]:
#Ce fichier doit être retiré du dossier models vers le workspace principal pour qu'il séexécute correctement
import pandas as pd
import numpy as np
import pickle 
import os.path
from pickled import *
from sklearn.preprocessing import MinMaxScaler
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

In [2]:
data = pd.read_csv('dodo.csv',header=None)
data.head()

,0,1,2,3,4,5,6,7,8,9,...,21,22,23,24,25,26,27,28,29,30
0,10.163,13.003,10.208,8.411,12.385,15.166,14.602,8.880,11.223,12.988,...,8.295,12.474,-0.194,13.427,2.268,0.617,1.723,1.327,3.270,11.538
1,5.958,4.603,10.742,10.881,12.890,13.133,12.188,11.788,13.458,13.396,...,6.989,12.833,2.032,12.000,2.399,0.365,2.018,2.031,1.888,11.075
2,13.577,13.916,19.037,10.794,15.338,19.827,16.489,12.529,16.101,14.389,...,11.852,13.609,-0.074,15.044,2.033,2.259,1.771,1.810,1.666,15.029
3,8.450,12.192,12.672,10.732,11.974,13.774,11.411,12.504,12.852,14.361,...,9.303,12.070,-0.101,13.414,1.886,1.624,1.948,1.811,1.581,12.317
4,5.651,13.475,12.742,13.640,11.611,5.052,6.040,7.804,7.767,11.026,...,6.881,12.439,1.042,11.647,1.786,2.237,2.126,1.297,2.017,10.529

In [3]:
for i in range(10000) :
    data.loc[i,23] = int(round(data.loc[i,23],0))
    if(data.loc[i,23] == 3) :
        data.loc[i,23] = 2
    if(data.loc[i,23] == -1) :
        data.loc[i,23] = 0
    for j in range(25,30) :
        data.loc[i,j] = round(data.loc[i,j])
        if data.loc[i,j] == 0 :
            data.loc[i,j] = 1
        if data.loc[i,j] == 6 :
            data.loc[i,j] = 5

In [4]:
X = data.loc[:,:23]
X.columns = ['ANALYSE 1','ANALYSE 2','ALGEBRE 2','PROCE FABRIC/DESSIN TECHN','ANALYSE DES CIRCUI /OPTIQ','ALGEBRE 1','CHIMIE','ELECTRICITE','THERMODYNAMIQUE','LANGUES','TECHNI D\'EXPRESS & COMMU1','Mécanique du point','ELECTROMAGNETISME','ELECTRONIQUE','ANALYS NUMER /PROB & STAT','ALGORITHMIQUE & PROGRAMMA','BASE DE LA CONCEPTION','TECHNO/METALL ET THERMO','TECHNI DOC /PROD DOC/ENTR','DAO ET OUTILS DE MATLAB','ALGEBRE 3','MECANIQUE DU SOLIDE','TECHN D\'EXPRE ET DE COMM','FILIERE']
X = X.assign(MOYENNE=data.loc[:,30])
X.head()

,ANALYSE 1,ANALYSE 2,ALGEBRE 2,PROCE FABRIC/DESSIN TECHN,ANALYSE DES CIRCUI /OPTIQ,ALGEBRE 1,CHIMIE,ELECTRICITE,THERMODYNAMIQUE,LANGUES,...,ALGORITHMIQUE & PROGRAMMA,BASE DE LA CONCEPTION,TECHNO/METALL ET THERMO,TECHNI DOC /PROD DOC/ENTR,DAO ET OUTILS DE MATLAB,ALGEBRE 3,MECANIQUE DU SOLIDE,TECHN D'EXPRE ET DE COMM,FILIERE,MOYENNE
0,10.163,13.003,10.208,8.411,12.385,15.166,14.602,8.880,11.223,12.988,...,7.793,12.217,13.247,15.212,14.178,12.923,8.295,12.474,0.0,11.538
1,5.958,4.603,10.742,10.881,12.890,13.133,12.188,11.788,13.458,13.396,...,9.930,13.462,15.249,13.698,12.430,10.316,6.989,12.833,2.0,11.075
2,13.577,13.916,19.037,10.794,15.338,19.827,16.489,12.529,16.101,14.389,...,16.794,16.381,15.902,16.017,17.421,17.854,11.852,13.609,0.0,15.029
3,8.450,12.192,12.672,10.732,11.974,13.774,11.411,12.504,12.852,14.361,...,10.582,12.125,16.616,15.815,14.372,11.777,9.303,12.070,0.0,12.317
4,5.651,13.475,12.742,13.640,11.611,5.052,6.040,7.804,7.767,11.026,...,17.004,11.044,13.207,12.156,13.316,8.268,6.881,12.439,1.0,10.529

In [5]:
X.to_csv("temp csv/X_interest.csv")

In [6]:
Y = data.loc[:,25:29]
Y.columns = ['CONFIDENCE','INSERTIONSATISFACTION','RELATEDTOFIELD','CONDITIONS','SALAIRE']
Y = Y.assign(FILIERE=data.loc[:,23])
Y.head()

,CONFIDENCE,INSERTIONSATISFACTION,RELATEDTOFIELD,CONDITIONS,SALAIRE,FILIERE
0,2.0,1.0,2.0,1.0,3.0,0.0
1,2.0,1.0,2.0,2.0,2.0,2.0
2,2.0,2.0,2.0,2.0,2.0,0.0
3,2.0,2.0,2.0,2.0,2.0,0.0
4,2.0,2.0,2.0,1.0,2.0,1.0

In [7]:
X_indus_interest = X[X['FILIERE'] == 0]; X_meca_interest = X[X['FILIERE'] == 1] ; X_elec_interest = X[X['FILIERE'] == 2]
Y_indus_interest = Y[Y['FILIERE'] == 0] ; Y_meca_interest = Y[Y['FILIERE'] == 1] ; Y_elec_interest = Y[Y['FILIERE'] == 2]
X_indus_interest.drop(columns=['FILIERE'],inplace=True,axis=1); X_meca_interest.drop(columns=['FILIERE'],inplace=True,axis=1); X_elec_interest.drop(columns=['FILIERE'],inplace=True,axis=1)
Y_indus_interest.drop(columns=['FILIERE'],inplace=True,axis=1); Y_meca_interest.drop(columns=['FILIERE'],inplace=True,axis=1); Y_elec_interest.drop(columns=['FILIERE'],inplace=True,axis=1)

C:\Users\lenovo\anaconda3\envs\cleaned\lib\site-packages\pandas\core\frame.py:4901: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [8]:
#indus

Y_indus_interest = Y_indus_interest
scaler_indus_interest = MinMaxScaler()
Y_indus_interest = scaler_indus_interest.fit_transform(Y_indus_interest)
X_indus_interest_train, X_indus_interest_test, Y_indus_interest_train, Y_indus_interest_test = train_test_split(X_indus_interest,Y_indus_interest,test_size=0.2)
clf_indus_interest = RandomForestRegressor(n_estimators=100)
clf_indus_interest.fit(X_indus_interest_train, Y_indus_interest_train)
score_train = float("{:.2f}".format(clf_indus_interest.score(X_indus_interest_train, Y_indus_interest_train)))
print(score_train)
score_test = float("{:.2f}".format(clf_indus_interest.score(X_indus_interest_test, Y_indus_interest_test)))
print(score_test)
pickled(clf_indus_interest,"clf_indus_interest")

0.99
0.91

In [9]:
#meca

Y_meca_interest = Y_meca_interest
scaler_meca_interest = MinMaxScaler()
Y_meca_interest = scaler_meca_interest.fit_transform(Y_meca_interest)
X_meca_interest_train, X_meca_interest_test, Y_meca_interest_train, Y_meca_interest_test = train_test_split(X_meca_interest,Y_meca_interest,test_size=0.2)
clf_meca_interest = RandomForestRegressor(n_estimators=100)
clf_meca_interest.fit(X_meca_interest_train, Y_meca_interest_train)
score_train = float("{:.2f}".format(clf_meca_interest.score(X_meca_interest_train, Y_meca_interest_train)))
print(score_train)
score_test = float("{:.2f}".format(clf_meca_interest.score(X_meca_interest_test, Y_meca_interest_test)))
print(score_test)
pickled(clf_meca_interest,"clf_meca_interest")

0.99
0.93

In [10]:
#elec

Y_elec_interest = Y_elec_interest
scaler_elec_interest = MinMaxScaler()
Y_elec_interest = scaler_elec_interest.fit_transform(Y_elec_interest)
X_elec_interest_train, X_elec_interest_test, Y_elec_interest_train, Y_elec_interest_test = train_test_split(X_elec_interest,Y_elec_interest,test_size=0.2)
clf_elec_interest = RandomForestRegressor(n_estimators=100)
clf_elec_interest.fit(X_elec_interest_train, Y_elec_interest_train)
score_train = float("{:.2f}".format(clf_elec_interest.score(X_elec_interest_train, Y_elec_interest_train)))
print(score_train)
score_test = float("{:.2f}".format(clf_elec_interest.score(X_elec_interest_test, Y_elec_interest_test)))
print(score_test)
pickled(clf_elec_interest,"clf_elec_interest")

0.99
0.92